### ISSUE TITLE
Cannot get streaming to work with TC358743 and B100

### ISSUE THREAD

**Issue by kevingarman** [antmicro/linux-tk1#1]
Hi,

I've compiled/installed your kernel.  I'm trying to use the TC358743 driver with the B100 from Auvidea (http://www.auvidea.eu/index.php/theme-styles/2014-12-30-22-32-06/b100-hdmi-to-csi-2-bridge) but so far its not working.  When I plug in the HDMI source I don't see any video devices under /dev/video*.  

Is there any reason it shouldn't work with the B100?  Where should I start troubleshooting?

Thanks,
Kevin

**Comment by wb1e** [comment]
Hi Kevin,
have you tried changing the i2c adapter id? B100 uses i2c:1 but the default port number for cameras is 2.
It is here: [linux-tk1/arch/arm/mach-tegra/board-ardbeg-sensors.c:435](https://github.com/antmicro/linux-tk1/blob/YUV_cameras/arch/arm/mach-tegra/board-ardbeg-sensors.c#L435).

**Comment by kevingarman** [comment]
Ah yes, thank you for pointing that out...I made the change and now I have /dev/video0!

Now when I view the video with gstreamer or VLC it acts like it's trying to start and then the system hangs.  I don't have much time to mess with this right now, but I'll try to get more info later.

**Comment by kevingarman** [comment]
...so I'm having a hard time getting a good log because my TK1 completely hangs, but attached is a picture of my screen when running gst with debug level 2.  I currently have nothing plugged into the hdmi port...I'm just trying to get a blank stream going first, then I'll find something to plug in.

Any thoughts?

![img_20160415_062135](https://cloud.githubusercontent.com/assets/2771634/14560083/ecbe36b6-02d2-11e6-9766-823287d74db0.jpg)

**Comment by wb1e** [comment]
In order to see the full log, you have to plug in serial cable to J1A2 DB-9 connector.
This chip won't stream the image without any input connected.
What is your planned source of HDMI input, framerate and resolution? TC38743 is vulnerable when it comes to input signal parameters...

**Comment by kevingarman** [comment]
Good point...I didn't think about a serial port.  I hope to run 1080p60 from a camcorder.  For some reason the HDMI out on the camera isn't starting so I thought I start with a blank image, but if that won't work I'll find another HDMI source for testing.  I'll let you know how it goes.

**Comment by kevingarman** [comment]
I see video!  I hooked my raspberry pi up as the HDMI source and I can finally see video coming from the TC358743.  Now I just have to figure out why my camera (Canon XA20) isn't playing nice.  It seems like it's waiting to detect something (that it's not getting) on its HDMI interface before it starts sending video.

Another question...do know of a way that I can cleanly handle HDMI disconnects?  If I'm capturing and the source it unplugged, the Jetson hangs.

**Comment by mgielda** [comment]
Hi Kevin, great to hear that. Jetson hangs because the Nvidia decoder part (VI driver) hangs when there is no MIPI-CSI2 signal. In our use case this is not a problem as we have a continuous stream but if you plan to connect and disconnect cables you would have to implement the interrupt that the Toshiba chip generates when the cable is connected/disconnected (and then propagate this info to lower layers so that the streaming stops) - or maybe quickly switch TC to test mode (pattern generator) - I see a number of options.

**Comment by wuestenarchitekten** [comment]
Hi @wojtekbe 
I thought maybe I can get some info here - have been trying to get the same board running on a Hummingboard with no success and can't seem to get help from Auvidea - do you by any chance have information on how to solve this issue in the https://github.com/SolidRun/linux-fslc kernel? 
Thank you very much
Markus

**Comment by robross0606** [comment]
Has anyone had any success implementing the interrupt that the Toshiba chip generates when the cable is connected/disconnected?

**Comment by robross0606** [comment]
Also, has anyone attempted to port this work to the TX1?

**Comment by robross0606** [comment]
While I have this working with a little extra effort, I have a question about apparent conflicts with `nvhost_vi`.  When I follow along with the [AntMicro Blog](http://antmicro.se/Blog/2015/09/jetson-tk1-cameras/) and `insmod` the relevant modules, I get an error when doing so with `tegra_camera.ko`:

`
ERROR: could not insert 'tegra_camera': Device or resource busy
`

I also get a corresponding error in the kernel log:

`
Error: Driver 'vi' is already registered, aborting...
`

However, if I `rmmod nvhost_vi` first, the Blog recommendations work fine.  Do I just need to blacklist `nvhost_vi` or was there another step in  `make menuconfig` that I missed?  Or is `tegra_camera` not the right module to use and I'm supposed to use `nvhost_vi` somehow?

**Comment by pgielda** [comment]
Hi @robross0606,

Thanks for the suggestion - we've updated the blog to contain "rmmod nvhost_vi" as this module is conflicting with "tegra_camera" that we are using for the Toshiba TC358743.

Best regards,
Peter

**Comment by pgielda** [comment]
Hi @wuestenarchitekten,

We are not affiliated in any way with SolidRun, please ask on their github. I've never even seen it until today.

Having said that - we've run this chip successfully with Tegra T30 and Tegra TK1, I see no reason why it should not work with NXP/Freescale i.MX6 (but you never know until you try). You could probably even try to integrate our driver with i.MX6 kernel with some small modifications. But we've never tried with this particular code and i.MX6.

If you need commercial support for a specific embedded project please contact us at contact@antmicro.com

BR,
Peter

**Comment by robross0606** [comment]
@pgielda, 
I should also mention that if you've actually `depmod`'ed these modules, you just need to `modprobe tegra_camera` the rest seem to _come along for the ride_ via module dependency.  Ultimately, I just ended up replacing `nvhost_vi` with `tegra_camera`in /etc/modules.

**Comment by robross0606** [comment]
Recommend adding a successful `lsmod`example to the blog so we can see what it should look like.  For example, should `soc_camera_platform` have loaded?

**Comment by robross0606** [comment]
Suddenly getting issues with my B100 after loading the drivers:

```
kernel: [  304.829710] vi vi.0: initialized
kernel: [  304.831132] platform vi.1: Driver vi requests probe deferral
kernel: [  304.831154] soc-camera-pdrv soc-camera-pdrv.4: Probing soc-camera-pdrv.4
kernel: [  304.841869] tegra-i2c tegra12-i2c.1: no acknowledge from address 0xf
kernel: [  304.841996] i2c_wr:write reg error:reg=4,val=0
kernel: [  304.847648] tegra-i2c tegra12-i2c.1: no acknowledge from address 0xf
kernel: [  304.847748] i2c_wr:write reg error:reg=8502,val=0
kernel: [  304.852688] Write EDID: 128 (8)
kernel: [  304.852895] tegra-i2c tegra12-i2c.1: no acknowledge from address 0xf
kernel: [  304.852979] tc358743_write_edid:write reg error:reg=8c00,val=8
kernel: [  304.859151] tc358743_probe: Fail to write EDID to tc35874!
kernel: [  304.864919] tegra-i2c tegra12-i2c.1: no acknowledge from address 0xf
kernel: [  304.865097] i2c_wr:write reg error:reg=8544,val=0
kernel: [  305.370840] tegra-i2c tegra12-i2c.1: no acknowledge from address 0xf
kernel: [  305.370911] i2c_wr:write reg error:reg=8544,val=10
kernel: [  305.375729] tc358743: probe of 1-000f failed with error -1
kernel: [  305.377021] vi vi.0: Tegra camera driver loaded.
kernel: [  305.378793] vi vi.1: initialized
kernel: [  305.378804] soc-camera-pdrv soc-camera-pdrv.1: Probing soc-camera-pdrv.1
kernel: [  305.389966] vi vi.1: Supporting mbus format code 0x100e using RGBA 8-8-8-8
kernel: [  305.391631] vi vi.1: Tegra camera driver loaded.
```

Attempting to run the gst-launch command as documented on the blog yields the following error:

```
Setting pipeline to PAUSED ...
ERROR: Pipeline doesn't want to pause.
ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:v4l2src0: Could not negotiate format
Additional debug info:
gstbasesrc.c(2830): gst_base_src_start (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
Check your filtered caps, if any
Setting pipeline to NULL ...
Freeing pipeline ...
```

Commands that previously worked fine are now either failing or locking the entire TK1.  Any ideas?

**Comment by robross0606** [comment]
It looks like some type of EDID problem but the issue occurs no matter which HDMI cable I use, including ones that previously worked.

**Comment by mmalczak** [comment]
Hi, 
Could You please give me some reference how to enable tc358743 driver. 
I work with tx1.
I have been trying for two weeks, but nothing seems to be working
