### ISSUE TITLE
Tegra TX1 support

### ISSUE THREAD

**Issue by sani1486** [antmicro/linux-tk1#3]
Hello antmicro,
1. I would like to enable the ADV7280-M chip for TX1 . so Is this driver here is compatible with TX1 ? if not can anybody suggest me what i would need to make the driver work with TX1 ? 

2. I am trying to compile this kernel to be used on Jetsin TK1 . But i am not sure about the compilation process . should i compile it in TK1 or in some host linux pc ? 
[http://antmicro.com/blog/2015/09/jetson-tk1-cameras/](url)
I am following this link for compilation . Please advise
Best regards

**Comment by pgielda** [comment]
Dear Sani,

1. This kernel is a L4T-derived 3.10 Linux kernel for Tegra K1. Current version of a TX1 kernel (R28.1) is  based on a Linux 4.4 kernel. Often there are issues when moving drivers from an older kernel to a newer one but in principle it should be possible.
2. This is a standard Linux kernel sources in that matter. You can compile those sources both on a device itself (on an ARMv7) and cross compile it on a x86 machine. This is a general statement true for any ARM Linux kernel not just TK1.
To cross compile you of course need a cross compiler e.g. from here: https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads

I am closing this as it is not really an issue.

**Comment by sani1486** [comment]
Hello , if i would like to use it in l4t 24.2.1 where the kernel is 3.10.96 .  would it be as simple as just copying it in the right directory ?

**Comment by pgielda** [comment]
No, you also need to add it to Kconfig files and add code to board files that will tie the chip to right i2c address and MIPI-CSI port.

**Comment by sani1486** [comment]
alright , Thanks for your help.
